"""item notes

Revision ID: 0002itemnote
Revises: afd0c4cd0c7c
Create Date: 2026-10-04 16:14:16.596937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002itemnote'
down_revision = 'afd0c4cd0c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_note_item_id_item')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_item_note_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_note'))
    )
    with op.batch_alter_table('item_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_note_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###

    # 旧『メモ』欄(item.note)の内容を、備考として引き継ぐ(書いた人は最初のユーザー扱い)
    op.execute(sa.text(
        'INSERT INTO item_note (item_id, target, body, is_resolved, user_id, created_at) '
        'SELECT id, \'\', note, :resolved, (SELECT MIN(id) FROM "user"), CURRENT_TIMESTAMP '
        'FROM item WHERE note <> \'\' AND EXISTS (SELECT 1 FROM "user")'
    ).bindparams(resolved=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_note_item_id'))

    op.drop_table('item_note')
    # ### end Alembic commands ###
