"""initial schema

Revision ID: afd0c4cd0c7c
Revises: 
Create Date: 2026-10-03 18:06:54.623806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd0c4cd0c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('uses_color', sa.Boolean(), nullable=False),
    sa.Column('uses_size', sa.Boolean(), nullable=False),
    sa.Column('uses_variant_name', sa.Boolean(), nullable=False),
    sa.Column('is_printable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design')),
    sa.UniqueConstraint('name', name=op.f('uq_design_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('item_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_item_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('category_id', 'brand', 'item_no', name=op.f('uq_item_category_id'))
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('variant_name', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_variant_qty_nonneg')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_variant_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant')),
    sa.UniqueConstraint('item_id', 'color', 'size', 'variant_name', name=op.f('uq_variant_item_id'))
    )
    op.create_table('printed_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_printed_product_qty_nonneg')),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], name=op.f('fk_printed_product_design_id_design')),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], name=op.f('fk_printed_product_variant_id_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_printed_product')),
    sa.UniqueConstraint('design_id', 'variant_id', name=op.f('uq_printed_product_design_id'))
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('printed_product_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(variant_id IS NULL) <> (printed_product_id IS NULL)', name=op.f('ck_stock_movement_one_target')),
    sa.CheckConstraint('delta <> 0', name=op.f('ck_stock_movement_delta_nonzero')),
    sa.ForeignKeyConstraint(['printed_product_id'], ['printed_product.id'], name=op.f('fk_stock_movement_printed_product_id_printed_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_stock_movement_user_id_user')),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], name=op.f('fk_stock_movement_variant_id_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movement_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movement_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_batch_id'))

    op.drop_table('stock_movement')
    op.drop_table('printed_product')
    op.drop_table('variant')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('design')
    op.drop_table('category')
    # ### end Alembic commands ###
